force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled for maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing repairs</fullName>
            </value>
            <value>
                <fullName>Ready for use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Is_Air_conditioning__c.field-meta.xml
<CustomField>
    <fullName>Is_Air_conditioning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Air conditioning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FleetManagementController.cls
public with sharing class FleetManagementController {
    
    @AuraEnabled(cacheable=true)
    public static List<Bus__c> getBuses() {
        return [SELECT Id, Name, Year__c, Maximum_Capacity__c, Odometer_Reading__c, Is_Air_conditioning__c, Current_Status__c
                FROM Bus__c];
    }
    
    @AuraEnabled
    public static Decimal getResaleValue(String busId) {
        Bus__c bus = [SELECT Id, Year__c, Maximum_Capacity__c, Odometer_Reading__c, Is_Air_conditioning__c , Current_Status__c FROM Bus__c WHERE Id = :busId LIMIT 1];
        
        Decimal startingPrice = 0;
        
        if (bus != null && bus.Current_Status__c == 'Ready for use') {
            if (bus.Maximum_Capacity__c == 24) {
                startingPrice = 120000;
            } else if (bus.Maximum_Capacity__c == 36) {
                startingPrice = 160000;
            }
            
            Decimal mileageReduction = Math.max(0, (bus.Odometer_Reading__c - 100000) * 0.10);
            startingPrice -= mileageReduction;
            
            if (bus.Is_Air_conditioning__c ) {
                startingPrice *= 1.03;
            }
            
            if (bus.Year__c <= 1972) {
                startingPrice *= 1.34;
            }
        }
        
        return startingPrice;
    }
}